sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker login -u mohsenasm -p $DOCKER_PASSWORD && docker-compose -f spark-client-with-tpcds-docker-compose.yml build && docker-compose -f spark-client-with-tpcds-docker-compose.yml push
