version: "3"

services:
  tpc-ds: # 0
    image: mohsenasm/spark-on-yarn-cluster:tpc-ds.1.staging
    environment:
      data_path: "hdfs:///tpc-ds-files/data"
    command: /run.sh exit
    networks:
      - yarn_net
    volumes:
      - tpc-ds-files:/tpc-ds-files

  spark-client: # 0
    image: mohsenasm/spark-on-yarn-cluster:spark_client.1.staging
    environment:
      SERVICE_PRECONDITION: "resourcemanager:8088"
      SPARK_HOME: "/opt/spark"
      PYSPARK_PYTHON: "python3"
    ports:
      - 18080:18080
    command: exit
    networks:
      - yarn_net
    env_file:
      - ./hadoop-client.env
    volumes:
      - tpc-ds-files:/tpc-ds-files:ro
      - spark-history:/spark-history

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  tpc-ds-files:
  spark-history:

networks:
  yarn_net:
    driver: overlay
