version: "3.2"

services:
  resourcemanager: # 1
    image: mohsenasm/spark-on-yarn-cluster:resource_manager.1.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864"
    ports: # maybe cause security issue
      - 8088:8088
    expose:
      # - 8088
      - 8032
      - 8030
      - 8031
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env

  namenode: # 1
    image: mohsenasm/spark-on-yarn-cluster:name_node.1.staging
    ports:
      - 9870:9870
    expose:
      - 9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env

  historyserver: # 1
    image: mohsenasm/spark-on-yarn-cluster:history_server.1.staging
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env

  datanode1: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.1.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.role == manager

  datanode2: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.1.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.role != manager

  nodemanager1: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.1.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    deploy:
      mode: global
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.role == manager

  nodemanager2: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.1.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    deploy:
      mode: global
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.role != manager

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  yarn_net:
    driver: overlay
    attachable: true
