version: "3.2"

services:
  resourcemanager: # 1
    image: mohsenasm/spark-on-yarn-cluster:resource_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864"
    ports: # maybe cause security issue
      - 8088:8088
    expose:
      # - 8088
      - 8032
      - 8030
      - 8031
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==1

  namenode: # 1
    image: mohsenasm/spark-on-yarn-cluster:name_node.5.staging
    ports:
      - 9870:9870
    expose:
      - 9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==1

  historyserver: # 1
    image: mohsenasm/spark-on-yarn-cluster:history_server.5.staging
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==1

  # ------------------------- datanodes -------------------------

  datanode1: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.5.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==1

  datanode2: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.5.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==2

  datanode3: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.5.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==3

  datanode4: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.5.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==4

  datanode5: # n
    image: mohsenasm/spark-on-yarn-cluster:data_node.5.staging
    expose:
      - 9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==5

  # ------------------------- nodemanagers -------------------------

  nodemanager1: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==1

  nodemanager2: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==2

  nodemanager3: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==3

  nodemanager4: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==4

  nodemanager5: # n
    image: mohsenasm/spark-on-yarn-cluster:node_manager.5.staging
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    expose:
      - "1000-65535"
    networks:
      - yarn_net
    env_file:
      - ./hadoop.env
    deploy:
      placement:
        constraints:
          - node.labels.node-id==5

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  yarn_net:
    driver: overlay
    attachable: true
